# Generated by Django 5.1.1 on 2024-11-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='title',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='title',
            field=models.ManyToManyField(to='api.product'),
        ),
    ]
