# Generated by Django 5.1.1 on 2024-11-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_warehouse_title_warehouse_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='title',
            new_name='titles',
        ),
        migrations.AddField(
            model_name='product',
            name='num_group',
            field=models.IntegerField(default=0),
        ),
    ]
