# Generated by Django 5.1.1 on 2024-11-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_warehouse_titles_product_num_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='num_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='num_war',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.ManyToManyField(to='api.product')),
            ],
        ),
    ]
